version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
      target: builder
    ports:
      - "3000:3000"
    volumes:
      - ../../:/app
    working_dir: /app
    command: sh -c "go install github.com/air-verse/air@latest && air"
    environment:
      - GIN_MODE=debug
      - GO111MODULE=on
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=hotaku_db
      - JWT_SECRET=your-secret-key
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=hotaku_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 