version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile
      target: builder
    ports:
      - "${APP_PORT:-3000}:3000"
    volumes:
      - ../../:/app
    working_dir: /app
    command: sh -c "go install github.com/air-verse/air@latest && air"
    environment:
      - GIN_MODE=${GIN_MODE:-debug}
      - GO111MODULE=on
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - DB_NAME=${DB_NAME:-hotaku_db}
      - JWT_SECRET=${JWT_SECRET:-your-super-secure-jwt-secret-key-that-is-at-least-32-characters-long}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-rootpassword}
      - MYSQL_USER=${DB_USER:-root}
      - MYSQL_PASSWORD=${DB_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${DB_NAME:-hotaku_db}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 