name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run go vet
      run: go vet ./...

    - name: Run go fmt check
      run: |
        if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
          echo "❌ Code is not formatted. Run 'go fmt ./...' to fix:"
          gofmt -s -l .
          exit 1
        fi
        echo "✅ Code is properly formatted"

    - name: Run tests
      run: go test -v -race ./...

    - name: Build check
      run: go build -v .

  pr-info:
    name: PR Information
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: PR Details
      run: |
        echo "### 📋 Pull Request Information"
        echo "- **Title:** ${{ github.event.pull_request.title }}"
        echo "- **Author:** ${{ github.event.pull_request.user.login }}"
        echo "- **Branch:** ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}"
        echo "- **Commits:** ${{ github.event.pull_request.commits }}"
        echo "- **Files Changed:** ${{ github.event.pull_request.changed_files }}" 